### ISSUE TITLE
这个项目太棒了！不过遇到了一些小问题

### ISSUE THREAD

**Issue by kxbin** [zlyboy/wx-formdata#4]
当使用小程序自带的 `wx.request` 进行 `POST` 上传图片时，经过验证可以正常上传图片

```
let formData = new FormData();
formData.appendFile("file", filePath);  // filePath为小程序临时文件路径
let data = formData.getData();

wx.request({
    method: "POST",
    url: 'http://xxxx',
    header: {
        "Content-Type": data.contentType
    },
    data: data.buffer,
})
```

不过如果换成 `node` 的 `request` 模块的话，则无法正常上传图片。

请教一下，是我使用方法不正确吗，还是 `request` 模块本身兼容性的问题呢？

```
let formData = new FormData();
formData.appendFile("file", filePath);  // filePath为小程序临时文件路径
let data = formData.getData();

const request = require("request");

request({
    method: "POST",
    url: 'http://xxxx',
    headers: {
        "Content-Type": data.contentType
    },
    body: data.buffer,
})
```

报错如下：

```
Error: Argument error, options.body.
    at setContentLength (/var/user/node_modules/request/request.js:437:28)
    at Request.init (/var/user/node_modules/request/request.js:442:5)
    at new Request (/var/user/node_modules/request/request.js:127:8)
    at request (/var/user/node_modules/request/index.js:53:10)
    at Promise (/var/user/index.js:7:9)
    at new Promise (<anonymous>)
    at Runtime.exports.main [as handler] (/var/user/index.js:5:12)
    at Runtime.handleOnce (/var/runtime/node10/Runtime.engine.js:218:23)
    at Timeout.setTimeout [as _onTimeout] (/var/runtime/node10/Runtime.engine.js:55:12)
    at ontimeout (timers.js:436:11)
```

**Comment by kxbin** [comment]
刚才又测试了下，似乎是`云函数`环境的问题。

如果将图片传到 `云函数` 中进行`request`的`POST`，便会引发上诉报错。

**Comment by zlyboy** [comment]
我这边没有测试环境，看错误似乎是request在读取data.buffer的时候出错了。data.buffer是ArrayBuffer类型，云函数环境下转换成Buffer类型试试？
```
request({
    method: "POST",
    url: 'http://xxxx',
    headers: {
        "Content-Type": data.contentType
    },
    body: Buffer.from(data.buffer),
})
```

**Comment by kxbin** [comment]
> 我这边没有测试环境，看错误似乎是request在读取data.buffer的时候出错了。data.buffer是ArrayBuffer类型，云函数环境下转换成Buffer类型试试？
> 
> ```
> request({
>     method: "POST",
>     url: 'http://xxxx',
>     headers: {
>         "Content-Type": data.contentType
>     },
>     body: Buffer.from(data.buffer),
> })
> ```

@zlyboy  太神奇了，按照您说的方法，真的成功了，太感谢了！ 

确实是在`云函数`环境下，要进行一次`Buffer.from()`

谢谢，膜拜大佬:yum:
